### ISSUE TITLE
网易云不支持SSL么

### ISSUE THREAD

**Issue by jkjoy** [MoePlayer/APlayer-Typecho#20]
貌似是这样的吧

**Comment by wjm2038** [comment]
@jkjoy 海外不支持而已

**Comment by jkjoy** [comment]
我用的腾讯云，也不支持哦



发自我的小米手机
在 jm wang <notifications@github.com>，2017年9月13日 11:45写道：

@jkjoy<https://github.com/jkjoy> 海外不支持而已

**Comment by metowolf** [comment]
当前的版本已经支持
