### ISSUE TITLE
能不能把播放进度条做成这种带声波的？

### ISSUE THREAD

**Issue by philipsc** [MoePlayer/APlayer-Typecho#30]
![tim 20180104150157](https://user-images.githubusercontent.com/31801469/34553029-38de94aa-f160-11e7-9dba-d52ee2d892e7.png)

如题，现在的播放进度条就是一根线 看起来很单调，是不是可以美化一下，做成图片这样的声波进度条

**Comment by kn007** [comment]
恕我直言，我可不觉得这样哪里美了。。。
