### ISSUE TITLE
请问可以设置默认音量大小吗？

### ISSUE THREAD

**Issue by charm-v** [MoePlayer/APlayer-Typecho#31]
最近来博客的朋友老有人反馈我，总是会被背景音乐吓一跳，我自己去看的时候才了解到，插件的默认背景音乐在80%~90%，分贝确实大了些。找了插件的一些资料和文档，但是均没有找到播放器里对于音量大小的默认设置方法。

请问，有没有参数可以设置默认音量大小的？（https://www.cxiansheng.cn/server/306  这个是自己的博文地址，如果需要可以点击测试一下，默认音量确实大）

**Comment by nagatoyk** [comment]
打开Meting.min.js  
找到
`aplayers.push(new APlayer(c))`
修改成
`aplayers.push(new APlayer(c).volume(1))`

**Comment by charm-v** [comment]
好的，谢谢。

**Comment by charm-v** [comment]
已设置成功；

**Comment by metowolf** [comment]
目前可以使用 `volume` 进行限制
```
[Meting volume="0.7"]
[Music server="netease" id="27759600" type="song"/]
[/Meting]
```
