### ISSUE TITLE
正常插入网易云歌曲之后，显示Error Happens

### ISSUE THREAD

**Issue by iblueer** [MoePlayer/APlayer-Typecho#33]
链接：
https://www.maemo.cc/index.php/2018/01/14/ame-kemuri.html

歌曲链接：
http://music.163.com/#/song?id=513360721

<img width="670" alt="2018-01-14 16 22 50" src="https://user-images.githubusercontent.com/3581944/34914121-43c93b56-f947-11e7-9a63-e7be1e11a63e.png">

**Comment by iblueer** [comment]
不过我换成QQ音乐的播放源之后就能恢复正常了。

QQ音乐链接：
https://y.qq.com/n/yqq/song/001yYM0I30CzdP.html

**Comment by metowolf** [comment]
已知问题，需要更新到 2.0.4 版本

**Comment by iblueer** [comment]
好的，马上更新
