### ISSUE TITLE
打开配置面板出错欸。。。

### ISSUE THREAD

**Issue by zaglaw** [MoePlayer/APlayer-Typecho#35]
打开配置面板出错欸。。。

插件meting的配置信息没有找到
exception 'Typecho_Plugin_Exception' with message '插件meting的配置信息没有找到' in /home/public_html/var/Widget/Options.php:544
Stack trace:
#0 /home/public_html/var/Widget/Plugins/Config.php(103): Widget_Options->plugin('meting')
#1 /home/public_html/admin/options-plugin.php(12): Widget_Plugins_Config->config()
#2 {main}

**Comment by zaglaw** [comment]
而且原生编辑器无法使用&发现数据库有个表：metingv1
老版是meting

**Comment by metowolf** [comment]
大版本升级先禁用再启用一次插件
