### ISSUE TITLE
播放插件不显示了

### ISSUE THREAD

**Issue by iblueer** [MoePlayer/APlayer-Typecho#36]
<img width="450" alt="2018-02-05 20 03 09" src="https://user-images.githubusercontent.com/3581944/35803683-aa22a166-0aaf-11e8-86a7-a59c21be81bc.png">

昨天还正常工作的，今天打开博客突然发现原来显示播放插件的位置已经什么都没了。

**Comment by iblueer** [comment]
<img width="443" alt="2018-02-05 20 03 22" src="https://user-images.githubusercontent.com/3581944/35803724-c5a607b6-0aaf-11e8-8516-e0c28a491d3d.png">

如果禁用插件，可以看到文本。

**Comment by metowolf** [comment]
建议提供一个可以复现的页面

**Comment by iblueer** [comment]
https://www.maemo.cc/index.php/2018/02/03/sennnenn-no-hane.html

比如这个页面

**Comment by metowolf** [comment]
这个问题是上游的 Meting 解析出现问题，等待修复。

临时解决方案可以在设置中填写 cookie
```
appver=1.5.9; os=osx; channel=netease; __remember_me=true; osver=%E7%89%88%E6%9C%AC%2010.13.2%EF%BC%88%E7%89%88%E5%8F%B7%2017C88%EF%BC%89;
```

**Comment by iblueer** [comment]
谢谢，我先填上cookie

**Comment by iblueer** [comment]
发现填上cookie之后还是无法显示
