### ISSUE TITLE
刚刚升级了2.1.0之后发现无法识别QQ音乐列表

### ISSUE THREAD

**Issue by philipsc** [MoePlayer/APlayer-Typecho#43]
![playlist](https://user-images.githubusercontent.com/31801469/37007534-ace00892-2118-11e8-9b1d-5f13acca5239.jpg)
在文章页面输入QQ音乐播放列表之后插入如上的信息，没有识别出ID和type

**Comment by philipsc** [comment]
另外，含有播放器的页面首次打开无法自动加载播放器，必须手动刷新页面才会加载。

**Comment by metowolf** [comment]
QQ 音乐的应该是换了新的 URL，所以识别失败，下个版本会做修正。
至于播放器加载问题，能否邮件提供一下重现页面。

**Comment by philipsc** [comment]
https://www.v2ex.cc/about.html

发自我的 iPhone

在 2018年3月6日，09:36，METO <notifications@github.com<mailto:notifications@github.com>> 写道：


QQ 音乐的应该是换了新的 URL，所以识别失败，下个版本会做修正。
至于播放器加载问题，能否邮件提供一下重现页面。
