### ISSUE TITLE
第一首无法播放

### ISSUE THREAD

**Issue by zhaoyongtao** [MoePlayer/APlayer-Typecho#46]
单曲无法播放。专辑、歌手、歌单 、榜单中第一首无法播放，剩余歌曲正常。

系统、软件：
Win7 x64        Chrome 65

单曲浏览器console报错提示：
player.js:263 DOMException: The element has no supported sources.

**Comment by metowolf** [comment]
请提供一个可重现的地址

**Comment by zhaoyongtao** [comment]
@metowolf  在公司网络环境下，会出现此问题。个人网络正常。请关闭此issue
