### ISSUE TITLE
插件在页面不显示

### ISSUE THREAD

**Issue by FlickerMi** [MoePlayer/APlayer-Typecho#50]
地址：https://notemi.cn/ali-cloud-activity-the-lowest-78-yuan---month-quick-to-pull-out-the-wool.html

启用了在文章中添加了一个歌单，发布后在文章页中未能显示。

编辑文章：
<img src="http://7bv8dw.com1.z0.glb.clouddn.com/notemi/1.png"/>

文章页面：
<img src="http://7bv8dw.com1.z0.glb.clouddn.com/notemi/2.png"/>

**Comment by metowolf** [comment]
经确认，该主题 `sexful-publish` 没有规范输出 footer 部分，因此无法正确加载播放器。
请联系主题作者处理
