### ISSUE TITLE
TE1.2开发版，部分页面播放器不显示的问题

### ISSUE THREAD

**Issue by Waxxh** [MoePlayer/APlayer-Typecho#51]
应该是使用网易云的链接才会出现这样的问题，上次反应描述有误，麻烦大大再查看下是哪方面导致的；
不显示页面：https://waxxh.me/music/2/
显示页面：https://waxxh.me/music/3/

**Comment by metowolf** [comment]
目前网易云 API 对单 IP 限制了请求频率，所以有可能是后台没开启缓存导致访问量过高

**Comment by Waxxh** [comment]
@metowolf  后台开启了Redis缓存，如果换用MySQL或者更换音乐品质，能显示播放器的地方会不同，TE1.0版本时是全都正常显示的，然后升级到1.2似乎就出现了这个问题orz

**Comment by Waxxh** [comment]
新版已正常
