### ISSUE TITLE
插件不显示

### ISSUE THREAD

**Issue by myitmx** [MoePlayer/APlayer-Typecho#54]
文章
![qq 20180514203903](https://user-images.githubusercontent.com/19377656/39997957-26cf7226-57b7-11e8-9a4c-9ea04ac1aeed.png)

前台
![qq 20180514204057](https://user-images.githubusercontent.com/19377656/39998025-53afa144-57b7-11e8-9723-0fa9700fb434.png)

使用的模板是
![qq 20180514204153](https://user-images.githubusercontent.com/19377656/39998062-7159bf22-57b7-11e8-8e3f-faa7dad52bdc.png)

**Comment by metowolf** [comment]
该主题使用了 pjax，需要手动修改一下插件

详情可以查看作者说明 [我在用 Meting/APlayer/DPlayer/JWPlayer / 其他 插件的时候不生效怎么回事？](https://get233.com/archives/mirages-QAQ.html#menu_index_14)
