### ISSUE TITLE
自己改写的模板 不显示播放器

### ISSUE THREAD

**Issue by dugulingping** [MoePlayer/APlayer-Typecho#64]
演示：https://blog.icyuyan.net/index.php/not-fond/108.html
不显示 本人略会点php 但是不知从何地方下手修改 请大佬指点怎么修改主题
主题开源地址：https://blog.icyuyan.net/index.php/not-fond/hello-world.html

**Comment by metowolf** [comment]
footer 模板中没有正确注入
```
<?php $this->footer(); ?>
```

**Comment by dugulingping** [comment]
> footer模板中没有正确注入
> 
> ```
> <?php $this->footer(); ?>
> ```

谢谢作者大大  解决了问题
