### ISSUE TITLE
https加载播放器失败

### ISSUE THREAD

**Issue by ghost** [MoePlayer/APlayer-Typecho#65]
使用http时 播放器能正常使用
使用https则无法显示
是不支持https吗？还是哪里需要改动？

**Comment by metowolf** [comment]
登录 Typecho 后台 -> 设置 -> 基本设置 -> 站点地址改成 https 的域名

**Comment by ghost** [comment]
> 登录 Typecho 后台 -> 设置 -> 基本设置 -> 站点地址改成 https 的域名

你好，按你所说的站点地址改成 https 的域名之后，https域名访问，播放器仍然无法加载，请问是哪里问题？

**Comment by metowolf** [comment]
建议给出博客地址，以及测试页面方便调试

**Comment by ghost** [comment]
> 建议给出博客地址，以及测试页面方便调试

已解决 感谢
 Typecho 后台 -> 设置 -> 基本设置 -> 站点地址改成 https 的域名后
插件设置里的云解析地址也要改成https域名 之后就解决了

再次感谢
