### ISSUE TITLE
播放失败

### ISSUE THREAD

**Issue by ghost** [MoePlayer/APlayer-Typecho#66]
能显示但是播放失败
![image](https://user-images.githubusercontent.com/25114568/50505663-fd7ea200-0aaf-11e9-8f8c-fbd882b570f3.png)

请问如何解决？

**Comment by menhood** [comment]
我这里加载正常，你看看是不是网络问题 🌚

**Comment by ghost** [comment]
> 我这里加载正常，你看看是不是网络问题 🌚

好像突然又好了 昨天好像也是这样 有时好 有时加载不出来 可能是网咯问题吧

谢了

**Comment by metowolf** [comment]
建议 F12 打开控制台，将报错信息贴上来。
